name: Dev Build

on:
  push:
    branches:
    - 'Dev'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build exe file
      run: |
        pip install pyinstaller
        pyinstaller --onefile --noconsole UpdateWeather.py
    - name: Copy files to package
      run: |
        mkdir -p UpdateWeather
        cp dist/UpdateWeather.exe UpdateWeather/
        cp config.ini UpdateWeather/
        cp hidapi-win.zip UpdateWeather/
        cp -r img/ UpdateWeather/
        cp README.md UpdateWeather/

    - name: Compress release files
      run: |
        7z a -tzip UpdateWeather.zip UpdateWeather

    - name: Create release archive
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: UpdateWeather.zip