name: Dev Build and Release (JWT)

on:
  push:
    branches:
      - 'Dev'
    tags:
      - 'v*-dev'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build exe file
      run: |
        pip install pyinstaller
        pyinstaller --onefile --noconsole UpdateWeather.py

    - name: Copy files to package
      run: |
        mkdir -p UpdateWeather
        cp dist/UpdateWeather.exe UpdateWeather/
        cp config.ini UpdateWeather/
        cp hidapi-win.zip UpdateWeather/
        cp -r img/ UpdateWeather/
        cp README.md UpdateWeather/

    - name: Compress release files
      run: |
        7z a -tzip UpdateWeather-JWT.zip UpdateWeather

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UpdateWeather-JWT-${{ github.ref_name }}
        path: UpdateWeather-JWT.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1.14.0
      with:
        body: |
          UpdateWeather JWT Version - ${{ github.event.head_commit.message }}
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release archive
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: UpdateWeather-JWT.zip
        asset_name: UpdateWeather-JWT-${{ github.ref_name }}.zip
        tag: ${{ github.ref }}